In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("../02_adapter/out/forward-seven-number-summaries.tsv", sep="\t", index_col=0)
df

,0,1,2,3,4,5,6,7,8,9,...,237,238,239,240,241,242,243,244,245,246
count,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.0,10000.00,10000.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
2%,32.0,31.0,24.0,34.0,34.0,31.0,34.0,34.0,24.00,34.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
9%,37.0,37.0,36.0,37.0,38.0,37.0,37.0,37.0,36.91,37.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
25%,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.00,38.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
50%,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.00,38.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
75%,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.00,38.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
91%,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.00,38.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0
98%,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.0,38.00,38.0,...,21.0,19.0,29.0,22.0,22.0,24.0,26.0,34.0,34.0,34.0

In [40]:
# 最後の方はちょっとしかリードが残っていないので、数パーセント以下のところを削除する。
CUT_COUNT_PERCENT: float = 0.9

def cut_edge(_df: pd.DataFrame, _CUT_COUNT_PERCENT: float):
    max_count: int = int(_df.loc["count"][0])

    drop_colnum: int = int(_df.columns[-1])
    for col, data in enumerate(_df.loc["count"]):
        if data < max_count * _CUT_COUNT_PERCENT:
            drop_colnum = int(col)
            break

    filt_df = _df.drop([str(col) for col in _df.columns[drop_colnum:]], axis=1)
    return filt_df

filt_df = cut_edge(df, CUT_COUNT_PERCENT)

In [47]:
# 25%のQualityが20%を切るタイミングを探す
CUT_QUALITY_PERCENT = 20
CUT_QUALITY_LOCATION = 25

def quality_check(_df: pd.DataFrame, _CUT_QUALITY_PERCENT: int, _CUT_QUALITY_LOCATION: int) -> int:
    target_row = _df.loc[f"{str(_CUT_QUALITY_LOCATION)}%"]

    trunc_loc: int = int(target_row.keys()[-1])
    for col, data in target_row.items():
        if data < _CUT_QUALITY_PERCENT:
            trunc_loc = int(col) -1
            break

    return trunc_loc

quality_check(filt_df, CUT_QUALITY_PERCENT, CUT_QUALITY_LOCATION)

232

In [48]:
CUT_COUNT_PERCENT: float = 0.9
CUT_QUALITY_PERCENT = 25
CUT_QUALITY_LOCATION = 50

# FWD
tsv_path = "../02_adapter/out/forward-seven-number-summaries.tsv"
trunc_len_f = quality_check(cut_edge(pd.read_csv(tsv_path, sep="\t", index_col=0), CUT_COUNT_PERCENT), CUT_QUALITY_PERCENT, CUT_QUALITY_LOCATION)

# REV
tsv_path = "../02_adapter/out/reverse-seven-number-summaries.tsv"
trunc_len_r = quality_check(cut_edge(pd.read_csv(tsv_path, sep="\t", index_col=0), CUT_COUNT_PERCENT), CUT_QUALITY_PERCENT, CUT_QUALITY_LOCATION)

print(trunc_len_f)
print(trunc_len_r)

232
227